/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component, version } from 'react';
import { Button, Platform, StyleSheet, Text, View } from 'react-native';
import TNRNUcomPosPrinter from 'react-native-ucom-pos-printer';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--',
    text: '-- no text --'
  };
  componentDidMount() {
    TNRNUcomPosPrinter.sampleMethod('Testing', 123, (message) => {
      this.setState({
        moduleVersion: '',
        status: 'native callback received',
        message
      });
    });
    TNRNUcomPosPrinter.show('hihihi RYRY')
    TNRNUcomPosPrinter.getVersion((versionStr) => {
      this.setState({
        moduleVersion: versionStr
      })
    })
    // const printerModel = TNRNUcomPosPrinter.getPrinterManager().getPrinterModel();
    // this.setState({
    //   text: printerModel
    // })
  }
  print() {
    console.log(`print()`)
    TNRNUcomPosPrinter.print()
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Module Version</Text>
        <Text style={styles.instructions}>{this.state.moduleVersion}</Text>
        <Text style={styles.welcome}>☆TNRNUcomPosPrinter example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
        <Text style={styles.welcome}>☆TEXT☆</Text>
        <Text style={styles.instructions}>{this.state.text}</Text>
        <Button
          title="Print"
          onPress={() => this.print()}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
